services:
  # 1. NOTRE MOTEUR IA (OLLAMA)
  ollama:
    image: ollama/ollama:latest
    container_name: vibesport-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama # Sauvegarde le modèle pour ne pas le retélécharger à chaque fois
    healthcheck:
      test: [ "CMD", "ollama", "list" ]
      interval: 3s
      timeout: 3s
      retries: 10

  # 2. Téléchargeur Automatique du Modèle Llama 3.2
  ollama-pull:
    image: ollama/ollama:latest
    container_name: vibesport-ollama-pull
    environment:
      - OLLAMA_HOST=ollama:11434
    depends_on:
      ollama:
        condition: service_healthy # 🌟 Docker attend que le "healthcheck" d'Ollama soit au vert !
    command: pull llama3.2

  # 3. NOTRE APPLICATION (FASTAPI + FRONTEND)
  web:
    build: . # Construit l'image à partir de ton Dockerfile
    container_name: vibesport-web
    ports:
      - "8000:8000"
    environment:
      # On dit à FastAPI d'aller chercher l'IA sur le conteneur "ollama"
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy # FastAPI attend aussi qu'Ollama soit parfaitement prêt !

volumes:
  ollama_data: